/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GeoguessrCookies": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleMeetsLink": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackChannel": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}