/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "CreateParty": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GeoguessrCookies": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleMeetsLink": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PlayGame": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SlackBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackChannel": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackHandler": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "SlackRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SlackSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}